// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: api/jwt/jwt.proto

package jwt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJwtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
}

func (x *CreateJwtRequest) Reset() {
	*x = CreateJwtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_jwt_jwt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJwtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJwtRequest) ProtoMessage() {}

func (x *CreateJwtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_jwt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJwtRequest.ProtoReflect.Descriptor instead.
func (*CreateJwtRequest) Descriptor() ([]byte, []int) {
	return file_api_jwt_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJwtRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type CreateJwtReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateJwtReply) Reset() {
	*x = CreateJwtReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_jwt_jwt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJwtReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJwtReply) ProtoMessage() {}

func (x *CreateJwtReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_jwt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJwtReply.ProtoReflect.Descriptor instead.
func (*CreateJwtReply) Descriptor() ([]byte, []int) {
	return file_api_jwt_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJwtReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateJwtReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetJwtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetJwtRequest) Reset() {
	*x = GetJwtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_jwt_jwt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJwtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwtRequest) ProtoMessage() {}

func (x *GetJwtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_jwt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwtRequest.ProtoReflect.Descriptor instead.
func (*GetJwtRequest) Descriptor() ([]byte, []int) {
	return file_api_jwt_jwt_proto_rawDescGZIP(), []int{2}
}

func (x *GetJwtRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetJwtReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetJwtReply) Reset() {
	*x = GetJwtReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_jwt_jwt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJwtReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwtReply) ProtoMessage() {}

func (x *GetJwtReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_jwt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwtReply.ProtoReflect.Descriptor instead.
func (*GetJwtReply) Descriptor() ([]byte, []int) {
	return file_api_jwt_jwt_proto_rawDescGZIP(), []int{3}
}

func (x *GetJwtReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_api_jwt_jwt_proto protoreflect.FileDescriptor

var file_api_jwt_jwt_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x6a, 0x77, 0x74, 0x2f, 0x6a, 0x77, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77, 0x74, 0x22, 0x2f, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x25, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x4a, 0x77, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x21, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4a, 0x77, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x32, 0x7e, 0x0a, 0x03, 0x4a, 0x77, 0x74, 0x12, 0x3f, 0x0a, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77,
	0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77, 0x74, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x06, 0x47,
	0x65, 0x74, 0x4a, 0x77, 0x74, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x4a, 0x77, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x77, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x23, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x77, 0x74, 0x50, 0x01,
	0x5a, 0x16, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6a, 0x77, 0x74, 0x3b, 0x6a, 0x77, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_jwt_jwt_proto_rawDescOnce sync.Once
	file_api_jwt_jwt_proto_rawDescData = file_api_jwt_jwt_proto_rawDesc
)

func file_api_jwt_jwt_proto_rawDescGZIP() []byte {
	file_api_jwt_jwt_proto_rawDescOnce.Do(func() {
		file_api_jwt_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_jwt_jwt_proto_rawDescData)
	})
	return file_api_jwt_jwt_proto_rawDescData
}

var file_api_jwt_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_jwt_jwt_proto_goTypes = []interface{}{
	(*CreateJwtRequest)(nil), // 0: api.jwt.CreateJwtRequest
	(*CreateJwtReply)(nil),   // 1: api.jwt.CreateJwtReply
	(*GetJwtRequest)(nil),    // 2: api.jwt.GetJwtRequest
	(*GetJwtReply)(nil),      // 3: api.jwt.GetJwtReply
}
var file_api_jwt_jwt_proto_depIdxs = []int32{
	0, // 0: api.jwt.Jwt.CreateJwt:input_type -> api.jwt.CreateJwtRequest
	2, // 1: api.jwt.Jwt.GetJwt:input_type -> api.jwt.GetJwtRequest
	1, // 2: api.jwt.Jwt.CreateJwt:output_type -> api.jwt.CreateJwtReply
	3, // 3: api.jwt.Jwt.GetJwt:output_type -> api.jwt.GetJwtReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_jwt_jwt_proto_init() }
func file_api_jwt_jwt_proto_init() {
	if File_api_jwt_jwt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_jwt_jwt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJwtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_jwt_jwt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJwtReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_jwt_jwt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJwtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_jwt_jwt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJwtReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_jwt_jwt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_jwt_jwt_proto_goTypes,
		DependencyIndexes: file_api_jwt_jwt_proto_depIdxs,
		MessageInfos:      file_api_jwt_jwt_proto_msgTypes,
	}.Build()
	File_api_jwt_jwt_proto = out.File
	file_api_jwt_jwt_proto_rawDesc = nil
	file_api_jwt_jwt_proto_goTypes = nil
	file_api_jwt_jwt_proto_depIdxs = nil
}
